

name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Declare tags in variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: |
              ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}
              ghcr.io/${{ github.repository }}:latest
          platforms: |
              linux/arm64
              linux/amd64


#      - uses: mr-smithers-excellent/docker-build-push@v5
#        name: Build & push Docker image
#        with:
#          image: gensim
#          addLatest: true
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
